### ISSUE TITLE
Class::DBI is missing from the CPAN history page

### ISSUE THREAD

**Issue by ap** [book/CPANio#23]
That’s a huge omission. It was the reason DBIx::Class exists in the first place. It was *the* ORM, for years.

**Comment by book** [comment]
The [history of CPAN hosted on cpan.io](http://cpan.io/ref/cpan/history.html) is now updated directly from the [source](http://github.com/neilbowers/history-of-cpan).

This issue has been reponed there as: neilbowers/history-of-cpan#14.
