### ISSUE TITLE
Timeline format

### ISSUE THREAD

**Issue by ap** [book/CPANio#24]
The prose format of this page doesn’t work terribly well for its content, IMO. A timeline format would make it much easier to scan and much easier to get a sense of the unfolding of events, of the cadence and the rhythm at which things happened. Some of them came out of nowhere and others were a slow multi-party tango of cause and effect (cause and inspiration really) ricochetting back and forth, and this prose format just buries the currents under the surface of an ocean of text.

**Comment by neilbowers** [comment]
Yeah, at some point I'd like to map this into a JSON file, then have some JS for providing an interactive timeline, with some sort of overview.

It wasn't originally going to be so long, but people mailed me their memories about different parts, and I kinda pasted them together, roughly in order :-)

**Comment by book** [comment]
The [history of CPAN hosted on cpan.io](http://cpan.io/ref/cpan/history.html) is now updated directly from the [source](https://github.com/neilbowers/history-of-cpan).

This issue has been reported there as: neilbowers/history-of-cpan#15.
